### ISSUE TITLE
Modules 2 Week 3 Morning Session Code Review

### ISSUE THREAD

**Issue by huseyinbiyik** [kamzzy/todoApp#4]
That's a good project, and functioning very well. But there some small changes needs to be done. Here they are:

-In terms of accessibility, using a trash can icon would be more explanatory for the users when they want to delete a task.
<img width="1024" alt="Screen Shot 2022-05-10 at 10 21 11" src="https://user-images.githubusercontent.com/25887253/167573608-79ffc91e-4fc6-449a-bda9-19bcf041a44f.png">

-When editing a task, the localStorage does not save the new input.

**Comment by preciousakams** [comment]
thanks for the feedback
